# Generated by Django 2.1.2 on 2018-10-29 08:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMX_SUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sModel', models.CharField(max_length=20)),
                ('sFirmware', models.CharField(max_length=50)),
                ('device_output', models.CharField(max_length=100)),
                ('device_input', models.CharField(max_length=100)),
                ('sutinport2device', models.CharField(max_length=100)),
                ('sutoutput2device', models.CharField(max_length=100)),
                ('timing2deviceinput', models.CharField(max_length=100)),
                ('timing2deviceoutput', models.CharField(max_length=100)),
                ('hasScaler', models.BooleanField(default=True)),
                ('hasSwitch', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CTP1301_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=20)),
                ('inportnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CTP1301_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=20)),
                ('outportnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PR0808_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=20)),
                ('inportnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PR0808_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=20)),
                ('outportnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QDoutport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qport', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Qdpattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpattern', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quantum2QDoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantum_model', models.IntegerField()),
                ('qdport_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuantumDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qmodel', models.CharField(max_length=20)),
                ('qfirmware', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=20)),
                ('expres', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('edid', models.CharField(max_length=20)),
                ('dtd', models.CharField(max_length=20)),
                ('cvt', models.IntegerField()),
                ('rb', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('dmtid', models.CharField(max_length=20)),
                ('stdid', models.CharField(max_length=20)),
                ('cvtid', models.CharField(max_length=20)),
                ('vic', models.CharField(max_length=20)),
                ('hvic', models.CharField(max_length=20)),
                ('ar', models.CharField(max_length=20)),
                ('htot', models.CharField(max_length=20)),
                ('hres', models.CharField(max_length=20)),
                ('hspd', models.CharField(max_length=20)),
                ('hspw', models.CharField(max_length=20)),
                ('hspp', models.CharField(max_length=20)),
                ('scan', models.CharField(max_length=20)),
                ('vrat', models.FloatField()),
                ('vtot', models.CharField(max_length=20)),
                ('vres', models.CharField(max_length=20)),
                ('vspd', models.CharField(max_length=20)),
                ('vspw', models.CharField(max_length=20)),
                ('vspp', models.CharField(max_length=20)),
                ('pclk', models.FloatField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            managers=[
                ('resObject', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sut2Sutinport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssut', models.IntegerField()),
                ('ssutinport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sut2Sutouport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssut', models.IntegerField()),
                ('ssutoutport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sutinport2CTP1301',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutinport_id', models.IntegerField()),
                ('pr_inportid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sutinport2PR0808',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutinport_id', models.IntegerField()),
                ('pr_inportid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sutoutport2CTP1301',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutoutport_id', models.IntegerField()),
                ('pr_outportid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sutoutport2PR0808',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutoutport_id', models.IntegerField()),
                ('pr_outportid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sutport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timing2CTP1301input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_inport', models.IntegerField()),
                ('res', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing2CTP1301output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_outport', models.IntegerField()),
                ('res', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing2PR0808input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_inport', models.IntegerField()),
                ('res', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing2PR0808output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_outport', models.IntegerField()),
                ('res', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing2QDoutport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.IntegerField()),
                ('qdport', models.IntegerField()),
            ],
        ),
    ]
