# Generated by Django 2.1.2 on 2018-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videotoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amx_sut',
            name='device_input',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='amx_sut',
            name='device_output',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='amx_sut',
            name='sutinport2device',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='amx_sut',
            name='sutoutput2device',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='amx_sut',
            name='timing2deviceinput',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='amx_sut',
            name='timing2deviceoutput',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
